{
 "title": "FastNetMon Advanced TOP 10 Hosts v2",
 "description": "FastNetMon Advanced TOP 10 Hosts v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "MBPS IN" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    host c,\n    sum(bits_incoming) length)\nFROM $table\nWHERE host in (\n    SELECT host\n    FROM\n(\n        SELECT\n            host,\n            sum(bits_incoming) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY host\n        ORDER BY length DESC\n        LIMIT 7\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) as groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, host c, sum(bits_incoming) length FROM fastnetmon.host_metrics WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766) AND  host in (     SELECT host     FROM (         SELECT             host,             sum(bits_incoming) as length         FROM fastnetmon.host_metrics         WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766)          GROUP BY host         ORDER BY length DESC         LIMIT 7 )) GROUP BY t, c  ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "host_metrics"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "MBPS OUT" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    host c,\n    sum(bits_outgoing) length)\nFROM $table\nWHERE host in (\n    SELECT host\n    FROM\n(\n        SELECT\n            host,\n            sum(bits_outgoing) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY host\n        ORDER BY length DESC\n        LIMIT 7\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) as groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, host c, sum(bits_outgoing) length FROM fastnetmon.host_metrics WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766) AND  host in (     SELECT host     FROM (         SELECT             host,             sum(bits_outgoing) as length         FROM fastnetmon.host_metrics         WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766)          GROUP BY host         ORDER BY length DESC         LIMIT 7 )) GROUP BY t, c  ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "host_metrics"
    }
   ]
  },
  {
   "title": "Packets incoming",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps", "label": "PPS IN" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    host c,\n    sum(packets_incoming) length)\nFROM $table\nWHERE host in (\n    SELECT host\n    FROM\n(\n        SELECT\n            host,\n            sum(packets_incoming) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY host\n        ORDER BY length DESC\n        LIMIT 7\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) as groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, host c, sum(packets_incoming) length FROM fastnetmon.host_metrics WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766) AND  host in (     SELECT host     FROM (         SELECT             host,             sum(packets_incoming) as length         FROM fastnetmon.host_metrics         WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766)          GROUP BY host         ORDER BY length DESC         LIMIT 7 )) GROUP BY t, c  ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "host_metrics"
    }
   ]
  },
  {
   "title": "Packets outgoing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps", "label": "PPS OUT" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    host c,\n    sum(packets_outgoing) length)\nFROM $table\nWHERE host in (\n    SELECT host\n    FROM\n(\n        SELECT\n            host,\n            sum(packets_outgoing) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY host\n        ORDER BY length DESC\n        LIMIT 7))",
     "rawQuery": "SELECT t, groupArray((c, length)) as groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, host c, sum(packets_outgoing) length FROM fastnetmon.host_metrics WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766) AND  host in (     SELECT host     FROM (         SELECT             host,             sum(packets_outgoing) as length         FROM fastnetmon.host_metrics         WHERE metricDate >= toDate(1540412766) AND metricDateTime >= toDateTime(1540412766)          GROUP BY host         ORDER BY length DESC         LIMIT 7)) GROUP BY t, c  ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "host_metrics"
    }
   ]
  }
 ]
}