{
 "title": "FastNetMon Advanced TOP 10 ASNs",
 "description": "FastNetMon Advanced TOP 10 ASNs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "MBPS IN" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    asn_number c,\n    sum(bits_incoming) length)\nFROM $table\nWHERE asn_number in (\n    SELECT asn_number\n    FROM\n(\n        SELECT\n            asn_number,\n            sum(bits_incoming) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY asn_number\n        ORDER BY length DESC\n        LIMIT 10\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) AS groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 AS t, asn_number c, sum(bits_incoming) length FROM fastnetmon.asn_metrics_ipv4 WHERE metricDate >= toDate(1611437064) AND metricDateTime >= toDateTime(1611437064) AND asn_number in (     SELECT asn_number     FROM (         SELECT             asn_number,             sum(bits_incoming) as length         FROM fastnetmon.asn_metrics_ipv4         WHERE metricDate >= toDate(1611437064) AND metricDateTime >= toDateTime(1611437064)          GROUP BY asn_number         ORDER BY length DESC         LIMIT 10 )) GROUP BY t, c ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "asn_metrics_ipv4"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "MBPS OUT" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(bits_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    asn_number c,\n    sum(bits_outgoing) length)\nFROM $table\nWHERE asn_number in (\n    SELECT asn_number\n    FROM\n(\n        SELECT\n            asn_number,\n            sum(bits_outgoing) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY asn_number\n        ORDER BY length DESC\n        LIMIT 10\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) AS groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 AS t, asn_number c, sum(bits_outgoing) length FROM fastnetmon.asn_metrics_ipv4 WHERE metricDate >= toDate(1611437072) AND metricDateTime >= toDateTime(1611437072) AND asn_number in (     SELECT asn_number     FROM (         SELECT             asn_number,             sum(bits_outgoing) as length         FROM fastnetmon.asn_metrics_ipv4         WHERE metricDate >= toDate(1611437072) AND metricDateTime >= toDateTime(1611437072)          GROUP BY asn_number         ORDER BY length DESC         LIMIT 10 )) GROUP BY t, c ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "asn_metrics_ipv4"
    }
   ]
  },
  {
   "title": "Packets incoming",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps", "label": "PPS IN" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    asn_number c,\n    sum(packets_incoming) length)\nFROM $table\nWHERE asn_number in (\n    SELECT asn_number\n    FROM\n(\n        SELECT\n            asn_number,\n            sum(packets_incoming) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY asn_number\n        ORDER BY length DESC\n        LIMIT 10\n))",
     "rawQuery": "SELECT t, groupArray((c, length)) AS groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 AS t, asn_number c, sum(packets_incoming) length FROM fastnetmon.asn_metrics_ipv4 WHERE metricDate >= toDate(1611437089) AND metricDateTime >= toDateTime(1611437089) AND asn_number in (     SELECT asn_number     FROM (         SELECT             asn_number,             sum(packets_incoming) as length         FROM fastnetmon.asn_metrics_ipv4         WHERE metricDate >= toDate(1611437089) AND metricDateTime >= toDateTime(1611437089)          GROUP BY asn_number         ORDER BY length DESC         LIMIT 10 )) GROUP BY t, c ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "asn_metrics_ipv4"
    }
   ]
  },
  {
   "title": "Packets outgoing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps", "label": "PPS OUT" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$columns</font>(<br />    host c,<br />    <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"navajowhite\">length</font>)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> host <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> host<br />    <font color=\"darkorange\">FROM</font><br />(<br />        <font color=\"darkorange\">SELECT</font><br />            host,<br />            <font color=\"navajowhite\">sum</font>(packets_incoming) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">length</font><br />        <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />        <font color=\"darkorange\">GROUP BY</font> host<br />        <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">length</font> <font color=\"darkorange\">DESC</font><br />        <font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">10</font><br />))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$columns(\n    asn_number c,\n    sum(packets_outgoing) length)\nFROM $table\nWHERE asn_number in (\n    SELECT asn_number\n    FROM\n(\n        SELECT\n            asn_number,\n            sum(packets_outgoing) as length\n        FROM $table\n        WHERE $timeFilter \n        GROUP BY asn_number\n        ORDER BY length DESC\n        LIMIT 10))",
     "rawQuery": "SELECT t, groupArray((c, length)) AS groupArr FROM ( SELECT (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 AS t, asn_number c, sum(packets_outgoing) length FROM fastnetmon.asn_metrics_ipv4 WHERE metricDate >= toDate(1611437096) AND metricDateTime >= toDateTime(1611437096) AND asn_number in (     SELECT asn_number     FROM (         SELECT             asn_number,             sum(packets_outgoing) as length         FROM fastnetmon.asn_metrics_ipv4         WHERE metricDate >= toDate(1611437096) AND metricDateTime >= toDateTime(1611437096)          GROUP BY asn_number         ORDER BY length DESC         LIMIT 10)) GROUP BY t, c ORDER BY t, c) GROUP BY t ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "asn_metrics_ipv4"
    }
   ]
  }
 ]
}