{
 "title": "Per hostgroup traffic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, hostgroup_name, avg(bits_incoming) Bandwidth FROM \"fastnetmon\".\"total_hostgroup_metrics\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY hostgroup_name, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, hostgroup_name, avg(bits_outgoing) Bandwidth FROM \"fastnetmon\".\"total_hostgroup_metrics\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY hostgroup_name, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, hostgroup_name, avg(packets_incoming) Rate FROM \"fastnetmon\".\"total_hostgroup_metrics\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY hostgroup_name, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, hostgroup_name, avg(packets_outgoing) Rate FROM \"fastnetmon\".\"total_hostgroup_metrics\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY hostgroup_name, time ORDER BY time ASC"
    }
   ]
  }
 ]
}