{
 "title": "FastNetMon: Networks traffic",
 "description": "Metrics of FastNetMon Advanced with ClickHouse DB.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Network traffic incoming",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits_incoming)\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits_incoming) FROM fastnetmon.network_metrics WHERE metricDate >= toDate(1534169173) AND metricDateTime >= toDateTime(1534169173) GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "network_metrics"
    }
   ]
  },
  {
   "title": "Network Incoming packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets_incoming)\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets_incoming) FROM fastnetmon.network_metrics WHERE metricDate >= toDate(1534169173) AND metricDateTime >= toDateTime(1534169173) GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "network_metrics"
    }
   ]
  },
  {
   "title": "Network traffic Outgoing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits_outgoing)\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits_outgoing) FROM fastnetmon.network_metrics WHERE metricDate >= toDate(1534169173) AND metricDateTime >= toDateTime(1534169173) GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "network_metrics"
    }
   ]
  },
  {
   "title": "Network Outgoing packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets_outgoing)\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets_outgoing) FROM fastnetmon.network_metrics WHERE metricDate >= toDate(1534169173) AND metricDateTime >= toDateTime(1534169173) GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "network_metrics"
    }
   ]
  }
 ]
}