{
 "title": "Per network traffic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "protocol_version",
    "label": "Protocol Version",
    "query": "IPv4 : network_metrics, IPv4 per /24 : network_24_metrics_ipv4, IPv6 : network_metrics_ipv6"
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming per network traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, network, avg(bits_incoming) Bandwidth FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY network, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per network traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, network, avg(bits_outgoing) Bandwidth FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY network, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming per network packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, network, avg(packets_incoming) Rate FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY network, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per network packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, network, avg(packets_outgoing) Rate FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) GROUP BY network, time ORDER BY time ASC"
    }
   ]
  }
 ]
}