{
 "title": "Per ASN traffic",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "protocol_version",
    "label": "Protocol Version",
    "query": "IPv4 : asn_metrics_ipv4, IPv6 : asn_metrics_ipv6"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "total, udp, tcp, icmp, frgmented, tcp_syn"
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, concat(dictGetOrDefault('fastnetmon.asn_information', 'asn_name', asn_number, 'Unknown'), ' AS',toString(asn_number)), avg(multiIf('${protocol}' = 'total', bits_incoming, '${protocol}' = 'udp', udp_bits_incoming, '${protocol}' = 'tcp', tcp_bits_incoming, '${protocol}' = 'icmp', icmp_bits_incoming, '${protocol}' = 'fragmented', fragmented_bits_incoming, '${protocol}' = 'tcp_syn', tcp_syn_bits_incoming, 0)) as \" \" FROM \"fastnetmon\".\"$protocol_version\" WHERE asn_number in ( select asn_number from (\n\n  SELECT asn_number, sum(multiIf('${protocol}' = 'total', bits_incoming, '${protocol}' = 'udp', udp_bits_incoming, '${protocol}' = 'tcp', tcp_bits_incoming, '${protocol}' = 'icmp', icmp_bits_incoming, '${protocol}' = 'fragmented', fragmented_bits_incoming, '${protocol}' = 'tcp_syn', tcp_syn_bits_incoming, 0)) as length\n  FROM \"fastnetmon\".\"$protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n  GROUP BY asn_number\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY asn_number, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, concat(dictGetOrDefault('fastnetmon.asn_information', 'asn_name', asn_number, 'Unknown'), ' AS',toString(asn_number)), avg(multiIf (\n              '${protocol}' = 'total',\n              bits_outgoing,\n              '${protocol}' = 'udp',\n              udp_bits_outgoing,\n              '${protocol}' = 'tcp',\n              tcp_bits_outgoing,\n              '${protocol}' = 'icmp',\n              icmp_bits_outgoing,\n              '${protocol}' = 'fragmented',\n              fragmented_bits_outgoing,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_bits_outgoing,\n              0\n            )) as \" \" FROM \"fastnetmon\".\"$protocol_version\" WHERE asn_number in ( select asn_number from (\n\n  SELECT asn_number, sum(multiIf (\n              '${protocol}' = 'total',\n              bits_outgoing,\n              '${protocol}' = 'udp',\n              udp_bits_outgoing,\n              '${protocol}' = 'tcp',\n              tcp_bits_outgoing,\n              '${protocol}' = 'icmp',\n              icmp_bits_outgoing,\n              '${protocol}' = 'fragmented',\n              fragmented_bits_outgoing,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_bits_outgoing,\n              0\n            )) as length\n  FROM \"fastnetmon\".\"$protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n  GROUP BY asn_number\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY asn_number, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Incoming packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, concat(dictGetOrDefault('fastnetmon.asn_information', 'asn_name', asn_number, 'Unknown'), ' AS',toString(asn_number)), avg(multiIf (\n              '${protocol}' = 'total',\n              packets_incoming,\n              '${protocol}' = 'udp',\n              udp_packets_incoming,\n              '${protocol}' = 'tcp',\n              tcp_packets_incoming,\n              '${protocol}' = 'icmp',\n              icmp_packets_incoming,\n              '${protocol}' = 'fragmented',\n              fragmented_packets_incoming,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_packets_incoming,\n              0\n            )) as \" \" FROM \"fastnetmon\".\"$protocol_version\" WHERE asn_number in ( select asn_number from (\n\n  SELECT asn_number, sum(multiIf (\n              '${protocol}' = 'total',\n              packets_incoming,\n              '${protocol}' = 'udp',\n              udp_packets_incoming,\n              '${protocol}' = 'tcp',\n              tcp_packets_incoming,\n              '${protocol}' = 'icmp',\n              icmp_packets_incoming,\n              '${protocol}' = 'fragmented',\n              fragmented_packets_incoming,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_packets_incoming,\n              0\n            )) as length\n  FROM \"fastnetmon\".\"$protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n  GROUP BY asn_number\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY asn_number, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Outgoing packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, concat(dictGetOrDefault('fastnetmon.asn_information', 'asn_name', asn_number, 'Unknown'), ' AS',toString(asn_number)), avg(multiIf (\n              '${protocol}' = 'total',\n              packets_outgoing,\n              '${protocol}' = 'udp',\n              udp_packets_outgoing,\n              '${protocol}' = 'tcp',\n              tcp_packets_outgoing,\n              '${protocol}' = 'icmp',\n              icmp_packets_outgoing,\n              '${protocol}' = 'fragmented',\n              fragmented_packets_outgoing,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_packets_outgoing,\n              0\n            )) as \" \" FROM \"fastnetmon\".\"$protocol_version\" WHERE asn_number in ( select asn_number from (\n\n  SELECT asn_number, sum(multiIf (\n              '${protocol}' = 'total',\n              packets_outgoing,\n              '${protocol}' = 'udp',\n              udp_packets_outgoing,\n              '${protocol}' = 'tcp',\n              tcp_packets_outgoing,\n              '${protocol}' = 'icmp',\n              icmp_packets_outgoing,\n              '${protocol}' = 'fragmented',\n              fragmented_packets_outgoing,\n              '${protocol}' = 'tcp_syn',\n              tcp_syn_packets_outgoing,\n              0\n            )) as length\n  FROM \"fastnetmon\".\"$protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n  GROUP BY asn_number\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY asn_number, time ORDER BY time ASC "
    }
   ]
  }
 ]
}