{
 "title": "Top hosts in network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "select distinct(network) from fastnetmon.network_metrics union all select distinct(network) from fastnetmon.network_metrics_ipv6 union all select distinct(network) from fastnetmon.network_24_metrics_ipv4"
   },
   {
    "name": "ip_protocol_version",
    "label": "IP Protocol version",
    "query": "select if(position(':','$network') = 0, 'host_metrics', 'host_metrics_ipv6')"
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(bits_incoming) as \" \" FROM \"fastnetmon\".\"$ip_protocol_version\" WHERE host in ( select host from (\n\n  SELECT host, sum(bits_incoming) as length\n  FROM \"fastnetmon\".\"$ip_protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) and isIPAddressInRange(host, '$network')\n  GROUP BY host\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY host, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time,  host, avg(bits_outgoing) as \" \" FROM \"fastnetmon\".\"$ip_protocol_version\" WHERE host in ( select host from (\n\n  SELECT host, sum(bits_outgoing) as length\n  FROM \"fastnetmon\".\"$ip_protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) and isIPAddressInRange(host, '$network')\n  GROUP BY host\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY host, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Incoming packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(packets_incoming) as \" \" FROM \"fastnetmon\".\"$ip_protocol_version\" WHERE host in ( select host from (\n\n  SELECT host, sum(packets_incoming) as length\n  FROM \"fastnetmon\".\"$ip_protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) and isIPAddressInRange(host, '$network')\n  GROUP BY host\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY host, time ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Outgoing packet rate",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(packets_outgoing) as \" \" FROM  \"fastnetmon\".\"$ip_protocol_version\"  WHERE host in ( select host from (\n\n  SELECT host, sum(packets_outgoing) as length\n  FROM \"fastnetmon\".\"$ip_protocol_version\"\n  WHERE $__timeFilter(metricDateTime) AND ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) and isIPAddressInRange(host, '$network')\n  GROUP BY host\n  ORDER BY length DESC\n  LIMIT 10\n)) and $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime )\n GROUP BY host, time ORDER BY time ASC "
    }
   ]
  }
 ]
}