{
 "title": "FastNetMon: Total traffic",
 "description": "Metrics of FastNetMon Advanced with ClickHouse DB.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits)\nFROM $table\nWHERE $timeFilter AND direction = 'incoming'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'incoming' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Incoming packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets)\nFROM $table\nWHERE $timeFilter AND direction = 'incoming'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'incoming' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits)\nFROM $table\nWHERE $timeFilter AND direction = 'outgoing'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'outgoing' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Outgoing packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets)\nFROM $table\nWHERE $timeFilter AND direction = 'outgoing'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'outgoing' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Internal traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits)\nFROM $table\nWHERE $timeFilter AND direction = 'internal'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'internal' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Internal packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets)\nFROM $table\nWHERE $timeFilter AND direction = 'internal'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'internal' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Other traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (bits)\nFROM $table\nWHERE $timeFilter AND direction = 'other'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (bits) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'other' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  },
  {
   "title": "Other packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "metricDate",
     "dateTimeColDataType": "metricDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, SUM (packets)\nFROM $table\nWHERE $timeFilter AND direction = 'other'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(metricDateTime), 1) * 1) * 1000 as t, SUM (packets) FROM fastnetmon.total_metrics WHERE metricDate >= toDate(1534169095) AND metricDateTime >= toDateTime(1534169095) AND direction = 'other' GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "total_metrics"
    }
   ]
  }
 ]
}