{
 "title": "Traffic for specific host",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "protocol_version",
    "label": "Protocol Version",
    "query": "IPv4 : host_metrics, IPv6 : host_metrics_ipv6"
   },
   { "name": "host", "label": "IP address" }
  ]
 },
 "panels": [
  {
   "title": "Incoming per host traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(bits_incoming) Bandwidth FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per host traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(bits_outgoing) bandwidth FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming per host packet rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(packets_incoming) rate FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per host packet rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(packets_outgoing) Rate FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming per host flows",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(flows_incoming) flows FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per host flows",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(flows_outgoing) flows FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming per host traffic by type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(tcp_syn_bits_incoming) tcp_syn, avg(tcp_bits_incoming) as tcp, avg(udp_bits_incoming) as udp, avg(icmp_bits_incoming) as icmp, avg(fragmented_bits_incoming) as fragmented FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per host traffic by type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(tcp_syn_bits_outgoing) tcp_syn, avg(tcp_bits_outgoing) as tcp , avg(udp_bits_outgoing) as udp, avg(icmp_bits_outgoing) as icmp, avg(fragmented_bits_outgoing) as fragmented FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Incoming per host packet rate by type",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(tcp_syn_packets_incoming) tcp_syn, avg(tcp_packets_incoming) as tcp, avg(udp_packets_incoming) as udp, avg(icmp_packets_incoming) as icmp, avg(fragmented_packets_incoming) as fragmented FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Outgoing per host packet rate by type",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(metricDateTime) as time, host, avg(tcp_syn_packets_outgoing) tcp_syn, avg(tcp_packets_outgoing) as tcp, avg(udp_packets_outgoing) as udp, avg(icmp_packets_outgoing) as icmp, avg(fragmented_packets_outgoing) as fragmented FROM \"fastnetmon\".\"$protocol_version\" WHERE $__timeFilter(metricDateTime) AND   ( metricDateTime  >= $__fromTime AND metricDateTime <= $__toTime ) AND ( host = '$host' ) GROUP BY host, time ORDER BY time ASC"
    }
   ]
  }
 ]
}