{
 "title": "Per ASN traffic",
 "description": "Per ASN dashboard which uses Traffic Persistency in FastNetMon Advanced",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "asn", "label": "ASN", "query": "15169" }
  ]
 },
 "panels": [
  {
   "title": "Total traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE (srcAsn = $asn OR dstAsn = $asn)",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538673863) AND packetDateTime >= toDateTime(1538673863) AND  (srcAsn = 15169 OR dstAsn = 15169) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE (dstAsn = $asn)",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538673863) AND packetDateTime >= toDateTime(1538673863) AND  (dstAsn = 15169) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE (srcAsn = $asn)",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538673863) AND packetDateTime >= toDateTime(1538673863) AND  (srcAsn = 15169) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  }
 ]
}