{
 "title": "Per prefix traffic",
 "description": "Per prefix traffic based on FastNetMon Advanced Traffic Persistency ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "label": "Prefix", "query": "8.8.8.0" },
   { "name": "cidr", "label": "CIDR", "query": "24" }
  ]
 },
 "panels": [
  {
   "title": "Total traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE ((srcIp >= IPv4StringToNum('$prefix') AND srcIp <= IPv4StringToNum('$prefix') + toUInt32(exp2(32-$cidr))) or (dstIp >= IPv4StringToNum('$prefix') AND dstIp <= IPv4StringToNum('$prefix') + toUInt32(exp2(32-$cidr))))",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538675200) AND packetDateTime >= toDateTime(1538675200) AND  ((srcIp >= IPv4StringToNum('8.8.8.0') AND srcIp <= IPv4StringToNum('8.8.8.0') + toUInt32(exp2(32-24))) or (dstIp >= IPv4StringToNum('8.8.8.0') AND dstIp <= IPv4StringToNum('8.8.8.0') + toUInt32(exp2(32-24)))) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE dstIp >= IPv4StringToNum('$prefix') AND dstIp <= IPv4StringToNum('$prefix') + toUInt32(exp2(32-$cidr))",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538675200) AND packetDateTime >= toDateTime(1538675200) AND  dstIp >= IPv4StringToNum('8.8.8.0') AND dstIp <= IPv4StringToNum('8.8.8.0') + toUInt32(exp2(32-24)) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "fastnetmon",
     "dateColDataType": "packetDate",
     "dateTimeColDataType": "packetDateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "$rate( sum(length*sampleRatio*8) c) FROM $table WHERE srcIp >= IPv4StringToNum('$prefix') AND srcIp <= IPv4StringToNum('$prefix') + toUInt32(exp2(32-$cidr))",
     "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(packetDateTime), 20) * 20) * 1000 as t, sum(length * sampleRatio * 8) c FROM fastnetmon.traffic WHERE packetDate >= toDate(1538675200) AND packetDateTime >= toDateTime(1538675200) AND  srcIp >= IPv4StringToNum('8.8.8.0') AND srcIp <= IPv4StringToNum('8.8.8.0') + toUInt32(exp2(32-24)) GROUP BY t ORDER BY t)",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "traffic"
    }
   ]
  }
 ]
}