{
 "title": "FastNetMon Advanced Traffic for specified ASN",
 "description": "FastNetMon Advanced Traffic for specified ASN",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "asn", "label": "ASN", "query": "15169" },
   { "name": "protocol", "label": "Protocol version", "query": "ipv4,ipv6" }
  ]
 },
 "panels": [
  {
   "title": "Incoming traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/asns_traffic_$protocol$/",
     "query": "SELECT mean(\"bits_incoming\") FROM /asns_traffic_$protocol$/ WHERE (\"asn\" =~ /^$asn$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "bits_incoming" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "asn", "operator": "=~", "value": "/^$asn$/" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/asns_traffic_$protocol$/",
     "query": "SELECT mean(\"bits_incoming\") FROM \"hosts_traffic\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bits_outgoing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "asn", "operator": "=~", "value": "/^$asn$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "asns_traffic_$protocol",
     "query": "SELECT mean(\"packets_incoming\") FROM /asns_traffic_$protocol$/ WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "packets_incoming" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "asn", "operator": "=~", "value": "/^$asn$/" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "asns_traffic_$protocol",
     "query": "SELECT mean(\"bits_incoming\") FROM \"hosts_traffic\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_outgoing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "asn", "operator": "=~", "value": "/^$asn$/" }
     ]
    }
   ]
  }
 ]
}